# Generated by Django 5.2.8 on 2025-12-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='user', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
